### ISSUE TITLE
Write a better description of what libreport is in the README file.

### ISSUE THREAD

**Issue by yaccz** [abrt/libreport#176]
The current readme file is quite vague.

I had to go through the sources to understand it is library to file issues/bugs with common API to access various backends (currently bugzilla).

It would be nice to also mention what backends are supported (including versions) and what is the plan for future.

**Comment by jfilak** [comment]
It's been a long while since you had filed this issue. I hope README provides a better overview what libreport is about.

**Comment by jfilak** [comment]
I'm not closing this issue yet because there is still room for improvement.

**Comment by yaccz** [comment]
:+1:

**Comment by mzidek-gh** [comment]
Hi,

there is still room for improvement, but I  would prefer to close this issue, because there always will be some room for improvement and we do not want to have this opened forever. However feel free to reopen the issue or open a new if you want to suggest more specific changes in the README.

So closing this for now.

Thanks!
