### ISSUE TITLE
ignore "sensitive words": Store Bypass, IBRS_FW

### ISSUE THREAD

**Issue by kparal** [abrt/libreport#667]
These words were incorrectly detected as sensitive. See screenshot:

![abrt](https://user-images.githubusercontent.com/755451/91413568-9c423f80-e84b-11ea-852c-9db9043e63b6.png)

libreport-2.14.0-4.fc33.x86_64

**Comment by kparal** [comment]
I wonder why you check `cpuinfo` for sensitive information at all. Can there be **anything** private to the user (that you can detect by simple word matching)?

**Comment by mgrabovsky** [comment]
> I wonder why you check `cpuinfo` for sensitive information at all. Can there be **anything** private to the user (that you can detect by simple word matching)?

Good point. From the top of my head, I can't think of any ways to smuggle sensitive information into cpuinfo.

**Comment by xsuchy** [comment]
@kparal it is hard. Either we can look for just full words and add all combinations of pass, password and then people will claim that we missed: password_mysystem or DBPassword. I'll rather have false positives than have false negatives.
So for this part of the report ... I am afraid we cannot do anything.

Regarding cpuinfo...
The function is called `highligh_words_in_tabs()` and - yes - it search through all tabs.
I think we can leave out cpuinfo. And maybe put environ as the first tab, because that have the highest chance to have forbidden words.

**Comment by kparal** [comment]
If you leave out `cpuinfo`, then this discussion is irrelevant. But I don't understand your point about word matching. Are you saying that you can't add `vulnerability spec store bypass`, `speculative store bypass` and `IBRS_FW` into the words whitelist (and ideally only match them as full words)? If you're afraid that the user could have e.g. `My banking IBRS_FW password` envvar defined and you'd treat it as insensitive incorrectly, you can define that whitelist for a particular tab (so e.g. this is the whitelist for cpuinfo, this is the whitelist for mountinfo, etc).

The idea is to skip over false positives which are extremely common, like this case. Because of these, too many bugs end up marked as private needlessly.
